<section class="container">

<div class="row my-4">
    <section class="col mr-2">
        <h2 class="h5">Ajouter une nouvelle catégorie</h2>
        <!-- formulaire de création de catégorie -->
        <form action="index.php?page=add_category" method="POST">
            <div class="form-group">
                <label for="category">Catégorie</label>
                <input type="text" name="category" id="category" class="form-control">
            </div>

            <?php if(isset($error)): ?>
                <div class="alert alert-danger" role="alert">
                  <?= $error; ?>
                </div>
            <?php endif; ?>
            <div class="my-2">
                <button class="btn btn-dark my-3">Ajouter</button>
            </div>
        </form>
    </section>
    
    <section class="col">
        <h2 class="h5">Liste des catégories</h2>
        <ul>
            <?php foreach ($categories as $category): ?>
                <li><?= $category['name'] ?></li>
            <?php endforeach ?>
        </ul>
    </section>
    
</div>
</section>