<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Distorsion</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" type="text/css" />
</head>
<body>
<header class="p-3 text-bg-dark">
  
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>
        
        
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="?page=home" class="nav-link px-2 nav-link px-2 text-white">Accueil</a></li>
          <li><a href="?page=add_category" class="nav-link px-2 text-white">Catégories</a></li>
          <li><a href="?page=add_room" class="nav-link px-2 text-white">Salons</a></li>
          <li><a href="?page=private" class="nav-link px-2 text-white">Messages</a></li>
        </ul>

        <div class="text-end">
          <?php if(!isset($_SESSION['id'])){ ?>
          <button type="button" class="btn btn-outline-light me-2"><a href="?page=register" class="nav-link px-2">Créer un compte</a></button>
          <?php } else { ?>
           <?php if(isset($_SESSION['avatar'])): ?>
          <img style="width:50px; height:50px" src="uploads/<?= $_SESSION['avatar'] ?>">
          <?php endif; ?>
          <button type="button" class="btn btn-outline-light me-2"><a href="?page=profil" class="nav-link px-2">Mon profil</a></button>
          <?php } ?> 
          <?php if(!isset($_SESSION['id'])){ ?>
            <button type="button" class="btn btn-outline-light me-2"><a href="?page=login" class="nav-link">Se connecter<a/></button>
          <?php } else { ?>
            <button type="button" class="btn btn-warning"><a href="?page=logout" class="nav-link">Se déconnecter</a></button>
          <?php } ?>
        </div>
      </div>
    </div>
</header>  

    <main class="my-2">
        <!-- On inclut le code html spécifique de chacune des pages -->
        <?php $router->callActionFromRequest();?>
    </main>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"></script>
</body>
</html>