<section class="container"> 

<h2>Se connecter</h2>

    <form action="index.php?page=login" method="POST">
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">@</span>
            <input type="text" class="form-control" placeholder="Pseudo" aria-label="Username" aria-describedby="basic-addon1" name="login">
        </div>

        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Mot de passe :</label>
            <input type="password" class="form-control" id="exampleInputPassword1" name='password'>
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1" name="conncect">Rester connecté</label>
        </div>
              <button type="submit" class="btn btn-dark my-3">Connexion</button>
    </form>
</section>    