


<section class="col-9">
<form action="index.php?page=chat&id=<?=$_GET['id']; ?>" method="POST">
    <div class="form-floating">
      <textarea name="content" class="form-control" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 100px"></textarea>
      <label for="floatingTextarea2">Votre message</label>
    </div>
            <?php if(isset($error)): ?>
                        <div class="alert alert-danger" role="alert">
                          <?= $error; ?>
                        </div>
            <?php endif; ?>
            
        <div class="my-2">
            <button type="submit" class="btn btn-dark my-3">Envoyer</button>
        </div>    
</form>
        
        <?php foreach($messages as $message): ?>
            <div>
                <span class="badge text-bg-dark"><?= date_format(new DateTime($message['created_at']), 'd/m/Y - H:i:s') ?>
                
                </span>
                <p><?= $message['content'] ?></p>
            </div>
        <?php endforeach; ?>    
        
        
</section>