

<div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark" style="width: 280px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <svg class="bi pe-none me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
        <span class="fs-4">Utilisateurs</span>
    </a>
  <hr>
        <ul class="nav nav-pills flex-column mb-auto">
        
  <section class="container">  
        <?php foreach ($users as $user): ?>
          <li class="nav-item">
        <a href="#" class="nav-link text-white" aria-current="page">
          <li class="fs-4"><?= $user['login'] ?></li>
        </a>
            <button class="btn btn-warning btn-sm text-end" type="submit">Discussion</button>
        </li>
        <?php endforeach ?>
  </section>   

        </ul>
  <hr>
      
</div>

