<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Distorsion</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="public/css/style.css" type="text/css" />
</head>
<body>
    <header class="mx-3 d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <div class="col-md-3 mb-2 mb-md-0">
        <a href="index.php" class="d-inline-flex link-body-emphasis text-decoration-none">
          <h1>Distorsion</h1>
        </a>
      </div>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="?page=home" class="nav-link px-2 link-secondary">Accueil</a></li>
        <li><a href="?page=add_category" class="nav-link px-2">Catégories</a></li>
        <li><a href="?page=add_room" class="nav-link px-2">Salons</a></li>
      </ul>

      <div class="col-md-3 text-end">
        <?php if(!isset($_SESSION['id'])){ ?>
            <a href="?page=login" class="btn btn-outline-primary me-2">Se connecter</a>
            <a href="?page=register" class="btn btn-primary">Créer un compte</a>
        <?php } else { ?>
            <?php if(isset($_SESSION['avatar']) && $_SESSION['avatar'] != ''): ?>
                <img style="width:50px; height:50px" src="uploads/avatars/<?= $_SESSION['id'].'/'.$_SESSION['avatar'] ?>">
            <?php endif; ?>
            <a href="?page=profil" class="btn btn-primary">Mon profil</a>
            <a href="?page=logout" class="btn btn-outline-primary me-2">Se déconnecter</a>
        <?php } ?>
      </div>
    </header>
    <main class="my-2">
        <!-- On inclut le code html spécifique de chacune des pages -->
        <?php // require getRouteFromQuery() ?>
        <?php $router->callActionFromRequest(); ?>
    </main>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"></script>
</body>
</html>