
<section class="container">
    <!-- formulaire de création de compte -->
    <div class="row my-4">
        <section class="col">
            <h2 class="h5">Créer un compte</h2>
            <form action="index.php?page=login" method="POST">
                <div class="form-group">
                    <label for="login">Login</label>
                    <input type="text" name="login" id="login" class="form-control">
                </div>
                <div class="form-group">
                    <label for="password">Mot de passe</label>
                    <input type="password" name="password" id="password" class="form-control">
                </div>
                <div class="form-group">
                    <label for="connect">Rester connecté ?</label>
                    <input type="checkbox" name="connect" id="connect" value="true">
                </div>
                
                <div class="my-2">
                    <button class="btn btn-primary">Se connecter</button>
                </div>
            </form>
        </section>
    </div>

</section>