
<!-- formulaire de modification d'un utilisateur -->
<!-- les champs doivent être préremplis-->

<section class="container">
    <!-- formulaire de création de compte -->
    <div class="row my-4">
        <section class="col">
            <h2 class="h5">Modifier mon compte</h2>
            <form action="index.php?page=profil" method="POST" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="login">Login</label>
                    <input type="text" name="login" id="login" class="form-control" value="<?= $user['login']; ?>">
                    <?php if(isset($errors['login'])): ?>
                        <!-- afficher le message d'erreur -->
                        <div class="alert alert-danger" role="alert">
                          <?= $errors['login']; ?>
                        </div>
                    <?php endif; ?>
                    <?php if(isset($userAlreadyExist)): ?>
                        <!-- afficher le message d'erreur -->
                        <div class="alert alert-danger" role="alert">
                          <?= $userAlreadyExist; ?>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" name="email" id="email" class="form-control" value="<?= $user['email']; ?>">
                    <?php if(isset($errors['email'])): ?>
                        <!-- afficher le message d'erreur -->
                        <div class="alert alert-danger" role="alert">
                          <?= $errors['email']; ?>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="form-group">
                    <label for="first-name">Prénom</label>
                    <input type="text" name="first-name" id="first-name" class="form-control" value="<?= $user['first_name']; ?>">
                    <?php if(isset($errors['first-name'])): ?>
                        <!-- afficher le message d'erreur -->
                        <div class="alert alert-danger" role="alert">
                          <?= $errors['first-name']; ?>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="form-group">
                    <label for="last-name">Nom</label>
                    <input type="text" name="last-name" id="last-name" class="form-control" value="<?= $user['last_name']; ?>">
                    <?php if(isset($errors['last-name'])): ?>
                        <!-- afficher le message d'erreur -->
                        <div class="alert alert-danger" role="alert">
                          <?= $errors['last-name']; ?>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="form-group">
                    <label for="birthdate">Date de naissance</label>
                    <input type="date" name="birthdate" id="birthdate" class="form-control" value="<?= $user['birth_date']; ?>">
                    <?php if(isset($errors['birthdate'])): ?>
                        <!-- afficher le message d'erreur -->
                        <div class="alert alert-danger" role="alert">
                          <?= $errors['birthdate']; ?>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="form-group">
                    <label for="file">Image de profil</label>
                    <input type="file" name="file" id="file" class="form-control">
                </div>
                
                <!--Ajouter un input type file -->
                
                <div class="my-2">
                    <button class="btn btn-primary">Modifier</button>
                </div>
            </form>
        </section>
    </div>

</section>